# Generated by Django 6.0 on 2026-01-04 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_news_options_news_shop_sizes_news_views_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='shop_sizes',
        ),
    ]
